### ISSUE TITLE
Transfer npm package

### ISSUE THREAD

**Issue by mainanick** [refactoringui/heroicons#1]
I've been using tailwind for a while and can't wait for tailwind ui. My has always been less than 6kb since we started using tailwind.

I empty published in the two packages to reserve it for you guys and would like to transfer them to you.
```js 
npm i heroicons
```
 ```js
npm i heroicon
```

**Comment by ebxn** [comment]
Hi guys,

This is already available on npm under:

`npm install refactoringui/heroicons`

Cheers :)
