### ISSUE TITLE
md-phone icon is kind of broken

### ISSUE THREAD

**Issue by IsidroMar95** [refactoringui/heroicons#15]
the phone icon outline has very thick lines 
![image](https://user-images.githubusercontent.com/23019968/75688849-d0a2bd80-5c65-11ea-82f0-3ae1d43105a4.png)
compared to another icons eg: 
![image](https://user-images.githubusercontent.com/23019968/75688964-fdef6b80-5c65-11ea-8848-d357b508865d.png)
![image](https://user-images.githubusercontent.com/23019968/75688994-0d6eb480-5c66-11ea-9895-5a5ba1b5c015.png)

**Comment by codex-zaydek** [comment]
There is an outstanding issue concerning four outlined icons (see #11).

I was able to fix `phone` and `currency-dollar` in the Figma version here: https://github.com/refactoringui/heroicons/issues/8#issuecomment-593908561. Feel free to export those from Figma in the meantime.

**Comment by codex-zaydek** [comment]
This has been (very recently) fixed. Please refer to #11 for more information.

In order to not confuse people, I recommend closing this issue. 😀

**Comment by IsidroMar95** [comment]
> This has been (very recently) fixed. Please refer to #11 for more information.
> 
> In order to not confuse people, I recommend closing this issue. 😀

Yes, I saw that Adam or Steve fixed it, so thank you
