### ISSUE TITLE
Additional folder icons

### ISSUE THREAD

**Issue by dillingham** [refactoringui/heroicons#16]
A few additional folder icons would be really nice.
Would also be in keeping with the file icons.

- Add folder icon
- Open folder icon

Adding an open folder gives active state in tree views.

![download](https://user-images.githubusercontent.com/29180903/75808593-594c5700-5d55-11ea-9919-a8a87a2e65b6.png)

Adding a create folder icon syncs with the create file icon
![images](https://user-images.githubusercontent.com/29180903/75808602-5baeb100-5d55-11ea-8365-2cf9d20010d1.png)

**Comment by sschoger** [comment]
Just added the "create" folder 🤙

**Comment by dillingham** [comment]
@sschoger awesome thanks!
