### ISSUE TITLE
🥳 I built a viewer for Heroicons

### ISSUE THREAD

**Issue by codex-zaydek** [refactoringui/heroicons#2]
👉 https://heroicons.dev
👉 https://github.com/codex-src/heroicons-viewer

_Need React-ready Heroicons? You can use this library I also developed: https://github.com/codex-src/react-heroicons._

I thought Heroicons needed a web-based viewer — I’m constantly using http://feathericons.com so I wanted to build something similar.

I just built what you see above, like in a matter of hours, so it’s not polished yet. **If anyone wants to submit a PR request, please be my guest.**

I’d like to add:

- [x] Custom domain (https://heroicons.dev)
- [x] Search
- [x] Click to copy to the clipboard
- [x] Responsive
- [x] Dark mode
- [x] Support for solid icons

All feedback and suggestions welcome. I’d like to make this as representative of TailwindCSS/RefactoringUI as possible. If @adamwathan and Steve Schoger want to directly contribute or alter the aesthetic in any way to make it more representative of their brand, that too.

**Comment by m1guelpf** [comment]
Quick feedback: click to copy SVG would be awesome

**Comment by codex-zaydek** [comment]
Yes, will definitely add soon. Thanks!

**Comment by chrised123** [comment]
@codex-zaydek I can help you with this. Shall I cover the UI part to show that the icon is copied?

**Comment by mgambill** [comment]
Thanks for the inspiration:
https://heroicons-viewer.nmyvsn.net/

**Comment by codex-zaydek** [comment]
@chrised123 Thanks — more than anything I just want to have a convenient frontend to find and preview Heroicons. @mgambill’s works really well for now. But feel free to improve mine if you like!

**Comment by codex-zaydek** [comment]
> Quick feedback: click to copy SVG would be awesome

I just shipped this! 🚀 Please let me know if I can improve it further.

**Comment by michealjroberts** [comment]
This is awesome!

**Comment by sschoger** [comment]
Added a link to the readme file :+1:
