### ISSUE TITLE
Feature Request: Exit to App

### ISSUE THREAD

**Issue by mitchbne** [refactoringui/heroicons#21]
Looking to see an 'exit_to_app' equivalence, please.

![image](https://user-images.githubusercontent.com/37649155/78194142-b4da4380-74bf-11ea-820c-5c416a35d80e.png)

https://material.io/resources/icons/?search=exi&icon=exit_to_app&style=baseline

Trying to use this in place of a 'Logout' button on a sidebar nav.

**Comment by IsidroMar95** [comment]
I just found one and it's the one I use, I hope it works for you.
`<svg viewBox="0 0 20 20" fill="currentColor" focusable="false" aria-hidden="true" class="w-5 h-5 text-gray-700"><path d="M10 16a1 1 0 1 1 0 2c-4.411 0-8-3.589-8-8s3.589-8 8-8a1 1 0 1 1 0 2c-3.309 0-6 2.691-6 6s2.691 6 6 6zm7.707-6.707a.999.999 0 0 1 0 1.414l-3 3a.997.997 0 0 1-1.414 0 .999.999 0 0 1 0-1.414L14.586 11H10a1 1 0 1 1 0-2h4.586l-1.293-1.293a.999.999 0 1 1 1.414-1.414l3 3z" fill-rule="evenodd"></path></svg>`
![image](https://user-images.githubusercontent.com/23019968/77131358-0941e580-6a21-11ea-8bbd-24a285301119.png)

**Comment by mitchbne** [comment]
Closing. Resolved here as an icon called 'logout'.
 https://github.com/refactoringui/heroicons/commit/41bd40f1bd605dd1d71cf2a8b22c6c772c284d12
