### ISSUE TITLE
Moon Icon

### ISSUE THREAD

**Issue by markmead** [refactoringui/heroicons#22]
Already have the sun icon, now we need the moon

**Comment by codex-zaydek** [comment]
There is a moon icon — you can see from the repo’s homepage: https://github.com/refactoringui/heroicons.

I’ll be updating heroicons.dev shortly to reflect the recent commit (moon, among other icons, were corrupted so I pulled them from the site — they’re fixed now).

**Comment by markmead** [comment]
Ah I see @codex-zaydek. Thanks for the response, will close the issue.
