### ISSUE TITLE
Icon Request: Play / Pause / Stop

### ISSUE THREAD

**Issue by acairns** [refactoringui/heroicons#33]
Thank you for building a lovely icon set and giving it away for free! I found them via Tailwind UI and I'm currently refactoring a side project to use both Tailwind UI components and heroicons.

Few icons I've been unable to replace and thought I'd let you know were:
- Play
- Pause
- Stop
- Bold
- Italic
- Underline

**Comment by r-freeman** [comment]
+1 to this

**Comment by sschoger** [comment]
Added Play/Pause/Stop to both sets 🤙

![image](https://user-images.githubusercontent.com/2652515/80229553-9aa70780-861e-11ea-8d67-b8855d1e9e44.png)

Will consider Bold/Italic/Underline for a future release.

**Comment by acairns** [comment]
Perfect, thank you @sschoger! 👍
