### ISSUE TITLE
Icon request - Computer

### ISSUE THREAD

**Issue by Sinnbeck** [refactoringui/heroicons#34]
I could really use a computer icon or two

* Desktop (perhaps just a screen?)
* Laptop

**Comment by sschoger** [comment]
Added a desktop this morning

![image](https://user-images.githubusercontent.com/2652515/80229423-66cbe200-861e-11ea-9eef-7eaa04000dd0.png)

Will consider a laptop for a future release 🤙

**Comment by Sinnbeck** [comment]
Awesome! Looks really great! Cant wait :)
