### ISSUE TITLE
Icon Request: Closed eye

### ISSUE THREAD

**Issue by estevanmaito** [refactoringui/heroicons#35]
Currently there is an open eye icon. It would be nice to have a closed eye so this could be possible: 

![Two inputs with eye icon. The first is open and the second is closed](https://images.squarespace-cdn.com/content/v1/546aeb13e4b06c7939161700/1440516528543-4TBCXXHQ541XYLUMGDDQ/ke17ZwdGBToddI8pDm48kOy-JNiIumCZKXdSxJbpjHNZw-zPPgdn4jUwVcJE1ZvWEtT5uBSRWt4vQZAgTJucoTqqXjS3CfNDSuuf31e0tVHKDusdKyDsURnP7tXIusEMjWVF83V9Y4ob_mCdKUMlzG0nsU3dfn6w--du8-EjPUE/image-asset.png?format=500w)

**Comment by sschoger** [comment]
Added this morning 🤙
![image](https://user-images.githubusercontent.com/2652515/80229307-3d12bb00-861e-11ea-9100-9b5a6483316a.png)
