### ISSUE TITLE
React Heroicons

### ISSUE THREAD

**Issue by mainanick** [refactoringui/heroicons#4]
[WIP]
`yarn add react-heroicons`
```js
import ArrowDown from "react-heroicons/dist/MdArrowDown"
```
Looking to change import to 
```js
import ArrowDown from "react-heroicons/outline-md/ArrowDown"
```
```js
import { ArrowDown } from "react-heroicons/outline-md"
```

https://github.com/mainanick/react-heroicons

**Comment by codex-zaydek** [comment]
FWIW this is the pattern I’m currently using _with_ React to achieve the same effect, using `import * as Hero from "components/heroicons"`. You can see my reference implementation [here](https://github.com/codex-src/heroicons-viewer/tree/ce298699155b08d0d883957e51a5cf15afbae817/src/components/heroicons).

I’ve checked, and in production mode tree-shaking is supported, so you’re not paying for more than the icons you’re actually using. 👍

**Comment by codex-zaydek** [comment]
Heroicons has become essential to me so I also created the following: https://github.com/codex-src/react-heroicons.

There’s some documentation to get you started, but it’s a simple as:

1. `yarn add https://github.com/codex-src/react-heroicons`
2. `import * as Hero from "react-heroicons"`
3. `<Hero.AdjustmentsSolidSm className="w-8 h-8 ..." />`

I’m using this myself in at least two different projects, and it should support advanced features like `strokeWidth={...}` for outlined icons.

Feedback welcome!

**Comment by jacobwgillespie** [comment]
Adding another link here, if you use Styled Components, you may be interested in my project **Styled Icons** (https://styled-icons.js.org) - the Heroicons are available as `@styled-icons/heroicons-outline` and `@styled-icons/heroicons-solid`:

```typescript
// import all icons
import * as heroiconsOutline from '@styled-icons/heroicons-outline'
import * as heroiconsSolid from '@styled-icons/heroicons-solid'

// import individual icons
import {Bookmark} from '@styled-icons/heroicons-outline'
```

Icons are available as Styled Components, support TypeScript, etc: https://github.com/jacobwgillespie/styled-icons.

Note though that `styled-icons` requires using Styled Components, and wouldn't be suitable for providing vanilla React components.
