### ISSUE TITLE
Icon Request: Open in new window

### ISSUE THREAD

**Issue by elyas-bhy** [refactoringui/heroicons#42]

**Comment by ps73** [comment]
I think there is already an icon for that.

Search here https://heroicons.dev/ for 'external-link'

**Comment by elyas-bhy** [comment]
Awesome! I completely missed it.
Closing this issue.

**Comment by markkimsal** [comment]
For those coming from google and using v2, it's now called 'heroicon-o-arrow-top-right-on-square'
