### ISSUE TITLE
Importing SVGs to CRA breaks due to lack of XML namespace for SVG.

### ISSUE THREAD

**Issue by shafkathullah** [refactoringui/heroicons#68]
I am not sure whether to submit issue here or in create-react-app repo, anyway the lack of XML namespace `xmlns="http://www.w3.org/2000/svg"` in HeroIcons SVGs results import issue in CRA. Would you mind adding that to every icon?

**Comment by Sinnbeck** [comment]
https://github.com/refactoringui/heroicons/issues/40

**Comment by shafkathullah** [comment]
Duplicate of #40
