### ISSUE TITLE
How do we tell which are which?

### ISSUE THREAD

**Issue by skylerspark** [refactoringui/heroicons#9]
I noticed all the icons are in the distributable area, but have No way to of knowing which are which, the previews dont work because the SVGs arent formatted/written correctly.

Im curious if maybe you have the time, you can add the icon names below the icons in the large list in readme.md

Otherwise makes it very hard to find icons

**Comment by CrashyBang** [comment]
This issue might help you for now: https://github.com/refactoringui/heroicons/issues/2

**Comment by codex-zaydek** [comment]
Just wanted to share that my viewer now support search: https://heroicons.dev.

Please let me know if there are further improvements I can make to the viewer. :smile:

**Comment by dillingham** [comment]
@codex-zaydek thanks a bunch for that. Might be nice to offer <path> only mode.
Often Im switching between icons to see which I like, changing just the path keeps the parent styles
Just a thought. Thanks again

**Comment by sschoger** [comment]
For now you should check out heroicons.dev 👍
