### ISSUE TITLE
Not possible to change stroke-width on Vue icon components

### ISSUE THREAD

**Issue by Jacobtims** [refactoringui/heroicons#952]
### Discussed in https://github.com/tailwindlabs/heroicons/discussions/946

<div type='discussions-op-text'>

<sup>Originally posted by **Jacobtims** March  9, 2023</sup>
I want to change the stroke-width of an icon on the Vue component.
Like this:
```
import { PlusIcon } from '@heroicons/vue/24/solid';

<PlusIcon class="h-5 w-5" stroke-width="2"/>
```

This unfortunately **doesn't work**. </div>

It's not possible to change the **stroke-width** of an icon when using the Vue.js package.

**Comment by adamwathan** [comment]
Hey! Yep right now we don't expose a prop for `stroke-width`. If you'd like to change the stroke width you can do so with CSS:

```
import { PlusIcon } from '@heroicons/vue/24/solid';

<PlusIcon class="h-5 w-5 stroke-2"/>
```

Hope that helps! Going to close as not a bug (this would be a new feature) and no plans to work on this at the moment.

**Comment by Jacobtims** [comment]
The `stroke-2` class doesn't work on the component.

**Comment by tsangaris** [comment]
`stroke-[4px]` or any amount for that matter will work just fine. So:

`<PlusIcon class="h-5 w-5 stroke-[2px]"/>`

**Comment by kbtomlinson** [comment]
For me it works, but only if you also include a stroke color. For example: 
`				<ArrowLeftIcon
					class="h-6 w-6 stroke-red-600 stroke-2 text-gray-900 hover:text-gray-600"
					aria-hidden="true"
				/>`
